const assert=require('node:assert/strict');
const {freshScenario,transition,scenarioStep,isComplete,validSavedScenarios,freshScenarios}=require('./generated/demo-scenarios.js');
const {initialExplorer,explorerReducer,parseExplorer}=require('./generated/demo-explorer-state.js');
const at='2026-09-18T10:00:00.000Z';let count=0;
function check(name,fn){fn();count++;console.log('PASS',name)}
function run(id,s,a){return transition(id,s,a,at)}
check('Finance requires start and correct role; illegal actions do not mutate data',()=>{let s=freshScenario('finance');let next=run('finance',s,{type:'submit',note:''});assert.equal(next.finance.status,'draft');assert.equal(next.events.length,0);s=run('finance',s,{type:'start'});s=run('finance',s,{type:'submit',note:'Kasir'});assert.equal(s.finance.status,'submitted');next=run('finance',s,{type:'approve'});assert.equal(next.finance.status,'submitted');assert.equal(next.events.length,1);});
check('Finance full flow is atomic and duplicates do not add audit events',()=>{let s=freshScenario('finance');for(const a of [{type:'start'},{type:'submit',note:'Kasir'},{type:'role',role:'manager'},{type:'approve'},{type:'role',role:'finance'},{type:'verify'}])s=run('finance',s,a);assert.equal(isComplete('finance',s),true);assert.equal(s.events.length,3);assert.ok(s.events.every(e=>e.code==='EXP-DEMO-001'));assert.equal(s.finance.reference,'SIM-PAY-001');assert.equal(run('finance',s,{type:'verify'}).events.length,3);});
check('Finance rejection requires reason and records decision',()=>{let s=freshScenario('finance');for(const a of [{type:'start'},{type:'submit',note:''},{type:'role',role:'manager'}])s=run('finance',s,a);assert.equal(run('finance',s,{type:'reject',reason:''}).finance.status,'submitted');s=run('finance',s,{type:'reject',reason:'Kebutuhan belum jelas'});assert.equal(s.finance.status,'rejected');assert.equal(run('finance',s,{type:'approve'}).finance.status,'rejected');});
check('Inventory rejects invalid quantity; preserves all 110 items at each step',()=>{let s=run('inventory',freshScenario('inventory'),{type:'start'});for(const quantity of [-1,0,101,1.5,NaN]){const n=run('inventory',s,{type:'dispatch',quantity});assert.equal(n.inventory.source,100);assert.equal(n.events.length,0);}s=run('inventory',s,{type:'dispatch',quantity:37});assert.deepEqual([s.inventory.source,s.inventory.transit,s.inventory.destination],[63,37,10]);assert.equal(run('inventory',s,{type:'dispatch',quantity:37}).events.length,1);s=run('inventory',s,{type:'role',role:'manager'});s=run('inventory',s,{type:'receive'});assert.deepEqual([s.inventory.source,s.inventory.transit,s.inventory.destination],[63,0,47]);assert.equal(run('inventory',s,{type:'receive'}).inventory.destination,47);});
check('Procurement rejects early payment, partial receiving, mismatched invoice and duplicate payment',()=>{let s=run('procurement',freshScenario('procurement'),{type:'start'});assert.equal(run('procurement',s,{type:'pay'}).procurement.status,'draft');s=run('procurement',s,{type:'order'});s=run('procurement',s,{type:'role',role:'staff'});assert.equal(run('procurement',s,{type:'goods',quantity:1}).procurement.status,'ordered');s=run('procurement',s,{type:'goods',quantity:2});s=run('procurement',s,{type:'role',role:'finance'});s=run('procurement',s,{type:'match',invoice:3500000});assert.equal(s.procurement.mismatch,true);assert.equal(run('procurement',s,{type:'pay'}).procurement.status,'received');const events=s.events.length;assert.equal(run('procurement',s,{type:'match',invoice:3500000}).events.length,events);s=run('procurement',s,{type:'match',invoice:3200000});assert.equal(s.procurement.status,'matched');s=run('procurement',s,{type:'pay'});assert.equal(isComplete('procurement',s),true);assert.equal(run('procurement',s,{type:'pay'}).events.length,s.events.length);});
check('Operations requires all four checks and records completion once',()=>{let s=run('operations',freshScenario('operations'),{type:'start'});assert.equal(run('operations',s,{type:'finish'}).operations.completed,false);for(let index=0;index<4;index++)s=run('operations',s,{type:'check',index,checked:true});assert.equal(scenarioStep('operations',s),1);assert.equal(run('operations',s,{type:'check',index:3,checked:true}).events.length,4);s=run('operations',s,{type:'finish'});assert.equal(s.operations.completed,true);assert.equal(s.events.length,5);assert.equal(run('operations',s,{type:'check',index:0,checked:false}).operations.checks[0],true);});
check('Persistence validates schema and stock conservation',()=>{const all=freshScenarios();assert.equal(validSavedScenarios(all),true);all.inventory.inventory.destination=90;assert.equal(validSavedScenarios(all),false);assert.equal(validSavedScenarios({}),false);assert.equal(validSavedScenarios(null),false);});
check('Legacy explorer parsing rejects broken state and keeps valid existing records',()=>{assert.ok(parseExplorer(initialExplorer()));assert.equal(parseExplorer({expenses:[]}),null);const s=initialExplorer();s.procurement[0].threeWayMatch=null;assert.equal(parseExplorer(s),null);});
check('Exploration role guards, audit references and idempotency',()=>{assert.equal(initialExplorer().currentRole,'director');let s=explorerReducer(initialExplorer(),{type:'role',role:'staff'});const meta={uid:'test-event',at};let n=explorerReducer(s,{type:'approve',id:'exp-1',...meta});assert.equal(n.expenses[0].status,'pending_manager');s=explorerReducer(s,{type:'role',role:'manager'});s=explorerReducer(s,{type:'approve',id:'exp-1',...meta});assert.equal(s.expenses[0].status,'pending_finance');assert.equal(s.auditLogs[0].docCode,'EXP-2026-081');assert.equal(explorerReducer(s,{type:'approve',id:'exp-1',...meta}).auditLogs.length,s.auditLogs.length);s=explorerReducer(s,{type:'role',role:'finance'});s=explorerReducer(s,{type:'verify',id:'exp-1',...meta});assert.equal(s.expenses[0].status,'verified_paid');assert.equal(s.auditLogs[0].docCode,'EXP-2026-081');});
check('Exploration procurement pays only matched docs under Finance role',()=>{let s=explorerReducer(initialExplorer(),{type:'role',role:'staff'});const meta={uid:'payment-event',at};assert.equal(explorerReducer(s,{type:'pay',id:'prc-2',...meta}).procurement[1].status,'3way_matched');s=explorerReducer(s,{type:'role',role:'finance'});assert.equal(explorerReducer(s,{type:'pay',id:'prc-1',...meta}).procurement[0].status,'po_issued');s=explorerReducer(s,{type:'pay',id:'prc-2',...meta});assert.equal(s.procurement[1].status,'paid');assert.equal(s.auditLogs[0].docCode,'PO-2026-039');});
console.log(`${count} domain checks passed`);
